name: csci-evae-workflow

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - '.github/workflows/app-workflow.yaml'
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - '.github/workflows/app-workflow.yaml'

jobs:
  project-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "20.9.0"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install --force

      - name: Build
        run: npm run build
        
  docker-build:
      if: ${{ github.ref == 'refs/heads/main' }}
      runs-on: ubuntu-latest
      needs: [project-build]
    
      steps:
        - uses: actions/checkout@v3
    
        - name: Set up Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '20.9.0'

        - name: Cache Node.js modules
          uses: actions/cache@v3
          with:
            path: |
              ~/.npm
              node_modules
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            restore-keys: ${{ runner.os }}-node
  
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2
    
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
    
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}
    
        - name: Build and push
          uses: docker/build-push-action@v4
          with:
            context: .
            file: dockerfile
            push: true
            tags: hsaad11/test1-frontend:latest
    
